//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EDL_CONFIG_DBEntities : DbContext
    {
        public EDL_CONFIG_DBEntities()
            : base("name=EDL_CONFIG_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EDL_DataProviderEnrollmentConfig> EDL_DataProviderEnrollmentConfig { get; set; }
    
        public virtual int EDL_GetInterfaceParameters(string interfaceName)
        {
            var interfaceNameParameter = interfaceName != null ?
                new ObjectParameter("InterfaceName", interfaceName) :
                new ObjectParameter("InterfaceName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EDL_GetInterfaceParameters", interfaceNameParameter);
        }

        public System.Data.Entity.DbSet<WebApplication.Models.ViewModel.ProviderUserModel> ProviderUserModels { get; set; }
    }
}
